=== gitpan/Apache-PageKit/eg/Content/Content.dtd
<!ELEMENT PAGE (CONTENT_VAR|CONTENT_LOOP)*>
<!ATTLIST PAGE
	cache		(yes|default|no)   "no">
<!ELEMENT CONTENT_VAR ANY>
<!ATTLIST CONTENT_VAR
        NAME                    CDATA   #REQUIRED>
<!ELEMENT CONTENT_LOOP (CONTENT_ITEM+)>
<!ATTLIST CONTENT_LOOP
        NAME                    CDATA   #REQUIRED>
<!ELEMENT CONTENT_ITEM (CONTENT_VAR*)>

=== gitpan/Apache-PageKit/eg/Content/xml/language.xml
<?xml version="1.0" ?>
<!DOCTYPE pagekit SYSTEM "../Content.dtd">
<PAGE>
<NAV_TITLE>Language Localization</NAV_TITLE>
<CONTENT_VAR NAME="html_title"><![CDATA[PageKit.org | Language Localization]]></CONTENT_VAR>
<CONTENT_LOOP NAME="demo_desc">
      <CONTENT_ITEM>
	<CONTENT_VAR NAME="feature"><![CDATA[Language Localization]]></CONTENT_VAR>

	<CONTENT_VAR NAME="description"><![CDATA[The language displayed is based
	on the
         user's preference, defaulting to the browser settings.]]></CONTENT_VAR>

      </CONTENT_ITEM>

    </CONTENT_LOOP>
<CONTENT_VAR NAME="title" xml:lang="en"><![CDATA[Title in English]]></CONTENT_VAR>
<CONTENT_VAR NAME="title" xml:lang="es"><![CDATA[Titulo en Espanol]]></CONTENT_VAR>
</PAGE>
