=== gitpan/Apache-PageKit/eg/Config/Config.dtd
<!ELEMENT CONFIG (GLOBAL,SERVERS,PAGES)>
<!ELEMENT GLOBAL EMPTY>
<!ATTLIST GLOBAL
	cache_dir			CDATA	"/tmp"
	cookies_not_set_page		CDATA	#IMPLIED
	default_lang			CDATA	"en"
	default_page			CDATA	"index"
	html_clean_level		(0|1|2|3|4|5|6|7|8|9)	"9"
	login_page			CDATA	"login"
	not_found_page			CDATA	#IMPLIED
	model_base_class		CDATA	"MyPageKit::Common"
	model_dispatch_prefix		CDATA	"MyPageKit::MyModel"
	post_max			CDATA	"100000000"
	recent_login_timeout		CDATA	"3600"
	uri_prefix			CDATA	#IMPLIED
	verify_page			CDATA	#IMPLIED>
<!ELEMENT SERVERS (SERVER)*>
<!ELEMENT SERVER EMPTY>
<!ATTLIST SERVER
	id			CDATA	"Default"
	cookie_domain		CDATA	#IMPLIED
	files_match		CDATA	#IMPLIED
	reload			(yes|no)	"no"
	search_engine_headers	(yes|no)	"no">
<!ELEMENT PAGES (PAGE)*>
<!ELEMENT PAGE EMPTY>
<!ATTLIST PAGE
        id                 ID      #REQUIRED
        browser_cache           CDATA   #IMPLIED
	fill_in_form		(yes|auto|no)	"auto"
        internal_title          CDATA   #IMPLIED
	in_use			(yes|no)	"yes"
        new_credential          CDATA   #IMPLIED
        parent_id               CDATA   #IMPLIED
	request_param_in_tmpl	CDATA	"no"
        require_login           CDATA   #IMPLIED
        template_cache		CDATA   #IMPLIED
        use_bread_crumb         CDATA   #IMPLIED
        use_template            CDATA   #IMPLIED
        uri_match		CDATA   #IMPLIED>

=== gitpan/Apache-PageKit/eg/Config/Config.xml
<?xml version="1.0" ?>
<!DOCTYPE CONFIG SYSTEM "./Config.dtd">
<CONFIG>
<GLOBAL
	login_page="login1"
	page_dispatch_prefix="MyPageKit::PageCode"
	component_dispatch_prefix="MyPageKit::ComponentCode"
	uri_prefix = "pagekit/"
/>
<SERVERS>
   <SERVER id="production"
	reload="no"
	cookie_domain=".pagekit.org"/>
   <SERVER id="staging"
	reload="yes"
	cookie_domain=".pagekit.org"/>
</SERVERS>
<PAGES>
  <PAGE id="customize" use_bread_crumb="yes" require_login="no" parent_id="examples">
  </PAGE>
  <PAGE id="examples" use_bread_crumb="yes" require_login="no" parent_id="index">
  </PAGE>
  <PAGE id="index" use_bread_crumb="no" require_login="no" template_cache="no">
  </PAGE>
  <PAGE id="license" use_bread_crumb="no" require_login="no" parent_id="index">
  </PAGE>
  <PAGE id="language" use_bread_crumb="yes" parent_id="examples">
  </PAGE>
  <PAGE id="login1" use_bread_crumb="yes" require_login="no" parent_id="examples">
  </PAGE>
  <PAGE id="login2" use_bread_crumb="no" require_login="no" parent_id="login1" error_page="login1" new_credential="yes">
  </PAGE>
  <PAGE id="newacct1" use_bread_crumb="yes" require_login="no" parent_id="examples">
  </PAGE>
  <PAGE id="newacct2" use_bread_crumb="yes" require_login="no" parent_id="newacct1" error_page="newacct1" new_credential="yes">    
  </PAGE>
</PAGES>
</CONFIG>
