=== gitpan/Apache-PageKit/eg/pagekit.dtd
<!ELEMENT SITE (PAGE*)>
<!ELEMENT PAGE (ATTR|VAR|LOOP)*>
<!ATTLIST PAGE
        page_id                 ID      #REQUIRED
        view                    CDATA   #REQUIRED
        browser_cache           CDATA   #IMPLIED
        domain                  CDATA   #IMPLIED
        error_page              CDATA   #IMPLIED
        error_page_run_code     CDATA   #IMPLIED
        internal_title          CDATA   #IMPLIED
        is_popup                CDATA   #IMPLIED
        is_secure               CDATA   #IMPLIED
        is_topdomain            CDATA   #IMPLIED
        nav_title               CDATA   #IMPLIED
        new_credential          CDATA   #IMPLIED
        page_id_match           CDATA   #IMPLIED
        parent_id               CDATA   #IMPLIED
        popup_width             CDATA   #IMPLIED
        popup_height            CDATA   #IMPLIED
        require_login           CDATA   #IMPLIED
        template_cache          CDATA   #IMPLIED
        use_nav                 CDATA   #IMPLIED
        use_template            CDATA   #IMPLIED>
<!ELEMENT ATTR ANY>
<!ATTLIST ATTR
        NAME                    CDATA   #REQUIRED>
<!ELEMENT TMPL_VAR ANY>
<!ATTLIST TMPL_VAR
        NAME                    CDATA   #REQUIRED>
<!ELEMENT TMPL_LOOP (TMPL_ITEM+)>
<!ATTLIST TMPL_LOOP
        NAME                    CDATA   #REQUIRED>
<!ELEMENT TMPL_ITEM (TMPL_VAR|TMPL_VAR_REF|TMPL_LOOP|TMPL_LOOP_REF)*>
<!ELEMENT TMPL_VAR_REF EMPTY>
<!ATTLIST TMPL_VAR_REF
	NAME			CDATA	#REQUIRED
	page_id_ref		CDATA	#REQUIRED
	NAME_REF		CDATA	#IMPLIED>
<!ELEMENT TMPL_LOOP_REF EMPTY>
<!ATTLIST TMPL_LOOP_REF
	NAME			CDATA	#REQUIRED
	page_id_ref		CDATA	#REQUIRED
	NAME_REF		CDATA	#IMPLIED>

=== gitpan/Apache-PageKit/eg/page.xml
<?xml version="1.0" ?>
<!DOCTYPE pagekit SYSTEM "./pagekit.dtd">
<SITE>
  <PAGE page_id = "customize"
    view = "std"
    use_nav = "yes"
    is_popup = "no"
    nav_title = "Customize"
    require_login = "no"
    parent_id = "examples"
    new_credential = "no">
    <TMPL_VAR NAME = "html_title">PageKit.org | Customize</TMPL_VAR>
  </PAGE>
  <PAGE page_id = "examples"
    view = "std"
    use_nav = "yes"
    is_popup = "no"
    nav_title = "Examples"
    require_login = "no"
    parent_id = "index"
    new_credential = "no">
    <TMPL_VAR NAME = "html_title">PageKit.org | Examples</TMPL_VAR>
  </PAGE>
  <PAGE page_id = "index"
    view = "std"
    use_nav = "no"
    is_popup = "no"
    nav_title = "Home"
    require_login = "no"
    cache = "normal"
    new_credential = "no">
    <TMPL_VAR NAME = "html_title">Welcome to PageKit.org</TMPL_VAR>
  </PAGE>
  <PAGE page_id = "license"
    view = "std"
    use_nav = "no"
    is_popup = "no"
    require_login = "no"
    parent_id = "index"
    new_credential = "no">
    <TMPL_VAR NAME = "html_title">RICOH SOURCE CODE PUBLIC LICENSE 1.0 - PageKit Application Framework</TMPL_VAR>
  </PAGE>
  <PAGE page_id = "login1"
    view = "std"
    use_nav = "yes"
    is_popup = "no"
    nav_title = "Login"
    require_login = "no"
    parent_id = "examples"
    new_credential = "no">
    <TMPL_VAR NAME = "html_title">PageKit.org | Login</TMPL_VAR>
  </PAGE>
  <PAGE page_id = "login2"
    view = "std"
    use_nav = "no"
    is_popup = "no"
    require_login = "no"
    parent_id = "login1"
    error_page = "login1"
    new_credential = "yes">
  </PAGE>
  <PAGE page_id = "newacct1"
    view = "std"
    use_nav = "yes"
    is_popup = "no"
    nav_title = "New Account"
    require_login = "no"
    parent_id = "examples"
    new_credential = "no">
    <TMPL_VAR NAME = "html_title">PageKit.org | New Account</TMPL_VAR>
  </PAGE>
  <PAGE page_id = "newacct2"
    view = "std"
    use_nav = "yes"
    is_popup = "no"
    nav_title = "Account Created"
    require_login = "no"
    parent_id = "newacct1"
    error_page = "newacct1"
    new_credential = "yes">
    <TMPL_VAR NAME = "html_title">PageKit.org | New Account</TMPL_VAR>
  </PAGE>
</SITE>
