=== gitpan/Apache-PageKit/eg/Controller/Config.dtd
<!ELEMENT CONFIG (GLOBAL,SERVERS,PAGES)>
<!ELEMENT GLOBAL EMPTY>
<!ATTLIST GLOBAL
	cookies_not_set_page	CDATA	#IMPLIED
	default_lang		CDATA	"en"
	default_page		CDATA	"index"
	fill_in_form		(yes|no)	"yes"
	include_dispatch_prefix	CDATA	"MyPageKit::IncludeCode"
	login_page		CDATA	"login"
	not_found_page		CDATA	#IMPLIED
	page_dispatch_prefix	CDATA	"MyPageKit::PageCode"
	post_max		CDATA	"100000000"
	recent_login_timeout	CDATA	"3600"
	uri_prefix		CDATA	#IMPLIED
	verify_page		CDATA	#IMPLIED>
<!ELEMENT SERVERS (SERVER)*>
<!ELEMENT SERVER EMPTY>
<!ATTLIST SERVER
	server_id		ID	"Default"
	cookie_domain		CDATA	#IMPLIED
	error_handler		(email|display|none)	"none"
	files_match		CDATA	#IMPLIED
	page_domain		(yes|no)	"no"
	reload			(yes|no)	"no"
	search_engine_headers	(yes|no)	"no"
	subdomain		CDATA	#IMPLIED>
<!ELEMENT PAGES (PAGE)*>
<!ELEMENT PAGE (ATTR)*>
<!ATTLIST PAGE
        page_id                 ID      #REQUIRED
        browser_cache           CDATA   #IMPLIED
        domain                  CDATA   #IMPLIED
        error_page              CDATA   #IMPLIED
        error_page_run_code     CDATA   #IMPLIED
        internal_title          CDATA   #IMPLIED
        is_popup                CDATA   #IMPLIED
        is_secure               CDATA   #IMPLIED
        is_topdomain            CDATA   #IMPLIED
        nav_title               CDATA   #IMPLIED
        new_credential          CDATA   #IMPLIED
        page_id_match           CDATA   #IMPLIED
        parent_id               CDATA   #IMPLIED
        popup_width             CDATA   #IMPLIED
        popup_height            CDATA   #IMPLIED
        require_login           CDATA   #IMPLIED
        template_cache		CDATA   #IMPLIED
        use_nav                 CDATA   #IMPLIED
        use_template            CDATA   #IMPLIED>
<!ELEMENT ATTR ANY>
<!ATTLIST ATTR
        NAME                    CDATA   #REQUIRED>

=== gitpan/Apache-PageKit/eg/Controller/Config.xml
<?xml version="1.0" ?>
<!DOCTYPE pagekit SYSTEM "./Config.dtd">
<CONFIG>
<GLOBAL
	login_page="login1"
	page_dispatch_prefix="MyPageKit::PageCode"
	module_dispatch_prefix="MyPageKit::ModuleCode"
	uri_prefix = "pagekit/"
	view_cache = "normal"/>
<SERVERS>
   <SERVER server_id="production"
	reload="no"
	cookie_domain=".pagekit.org"/>
   <SERVER server_id="staging"
	reload="yes"
	subdomain="staging"
	cookie_domain=".pagekit.org"/>
</SERVERS>
<PAGES>
  <PAGE page_id="customize" use_nav="yes" is_popup="no" nav_title="Customize" require_login="no" parent_id="examples" new_credential="no">
  </PAGE>
  <PAGE page_id="examples" use_nav="yes" is_popup="no" nav_title="Examples" require_login="no" parent_id="index" new_credential="no">
  </PAGE>
  <PAGE page_id="index" use_nav="no" is_popup="no" nav_title="Home" require_login="no" cache="normal" new_credential="no">
  </PAGE>
  <PAGE page_id="license" use_nav="no" is_popup="no" require_login="no" parent_id="index" new_credential="no">
  </PAGE>
  <PAGE page_id="language" use_nav="yes" is_popup="no" nav_title="Language Localization" parent_id="examples">
  </PAGE>
  <PAGE page_id="login1" use_nav="yes" is_popup="no" nav_title="Login" require_login="no" parent_id="examples" new_credential="no">
  </PAGE>
  <PAGE page_id="login2" use_nav="no" is_popup="no" require_login="no" parent_id="login1" error_page="login1" new_credential="yes">
  </PAGE>
  <PAGE page_id="newacct1" use_nav="yes" is_popup="no" nav_title="New Account" require_login="no" parent_id="examples" new_credential="no">
  </PAGE>
  <PAGE page_id="newacct2" use_nav="yes" is_popup="no" nav_title="Account Created" require_login="no" parent_id="newacct1" error_page="newacct1" new_credential="yes">    
  </PAGE>
</PAGES>
</CONFIG>
